<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Project;
use AppBundle\Entity\ProjectNote;
use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

  /**
   * @return Project[]
   */
  public function findAllProjectsOrderedByRecentlyActive(){

    return $this->createQueryBuilder('project')
      ->leftJoin('project.notes', 'project_note')
      ->orderBy('project_note.createdAt', 'DESC')
      ->getQuery()
      ->execute();
  }
}
