<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Project;
use AppBundle\Entity\ProjectNote;
use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectNoteRepository extends EntityRepository
{

  /**
   * @param Project $project
   *
   * @return ProjectNote[]
   */
  public function findAllRecentNotesForGenus(Project $project){
    
    return $this->createQueryBuilder('project_note')
      ->andWhere('project_note.project = :project')
      ->setParameter('project', $project)
      ->andWhere('project_note.createdAt > :recentDate')
      ->setParameter('recentDate', new \DateTime('-3 months'))
      
      ->getQuery()
      ->execute();
  }
}
